# Generated by Django 4.1.4 on 2022-12-13 00:36

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('login', '0003_createtodolist_alter_items_username_delete_username'),
    ]

    operations = [
        migrations.AlterField(
            model_name='createtodolist',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='tdlist', to=settings.AUTH_USER_MODEL),
        ),
    ]
